### ISSUE TITLE
adblockrules list

### ISSUE THREAD

**Issue by Dobbie03** [a2n-s/dotfiles#1]
Hi I am checking out your build of Surf and it keeps crashing asking for the adblockrules from ~/.surf/adblockrules.

Can you please share that.

Cheers

**Comment by Dobbie03** [comment]
Apologies, I placed this in the wrong repo.

**Comment by a2n-s** [comment]
Hi !

No worries about that :)

I do not use adblock on `surf` but do not have that much ads, as I use for instance `mpv` to play videos!

Cheers

**Comment by Dobbie03** [comment]
Thanks for the reply, You build calls for the following:

`surf-adblock: fatal: cannot read any rule from file /home/dobbie/.surf/adblockrules`

Cheers

**Comment by a2n-s** [comment]
Are you sure you talk about my [fork of surf](https://github.com/a2n-s/surf) or my [surf dotfiles](https://github.com/a2n-s/dotfiles/blob/.config/surf)?

Never seen this error or warning.

Tell me the steps you followed to reproduce the error :wink:

**Comment by Dobbie03** [comment]
Sorry I edited my previous comment.  I worked out what was going on.  I need to comple surf_adblock.  I am all under control now.

Thank you for replying.
